.\"
.\"
.\" Blame: Roland Dowdeswell <elric@imrryr.org>
.Dd May 28, 2009
.Os
.Dt KRB5_ADMIN 1
.Sh NAME
.Nm krb5_admin
.Nd kerberos administration tool
.Sh SYNOPSIS
.Nm
.Op Fl dlv
.Op Fl D Ar kdb
.Op Fl S Ar sqlitedb
.Op Fl h Ar hostspec
.Op Fl r Ar REALM
.Ar command Ar arg Oo Ar arg ... Oc
.Sh DESCRIPTION
.Nm
is used to make modifications to the Kerberos database, either remotely
via the
.Xr krb5_admind 8
daemon, or locally (with the
.Fl l
flag.)
.Pp
The options are as follows:
.Bl -tag -width indentxxxxxx
.It Fl D Ar kdb
specifies the location of the Kerberos DB when running against a local
database.
Defaults to the location built into the Kerberos libriares.
Implies
.Fl l .
.It Fl S Ar sqlitedb
specifies the location of the sqlite3 adjunct database where
.Nm
stores its additional schemas.
Can only be used if running against a local database.
.It Fl d
print debugging output.
.It Fl h Ar hostspec
connect to
.Ar hostspec
instead of searching for KDCs using the usual method.
A
.Ar hostspec
has a format of
.Oo Ar service@ Oc Ns Ar hostname Ns Oo : Ns Ar port Oc .
.It Fl r Ar REALM
connect to one of the KDCs for realm
.Ar REALM .
.It Fl l
operate on the local Kerberos DB.
.It Fl v
make the output a bit more verbose.
.El
.Pp
If no
.Ar command
is provided on the command line,
.Nm
will prompt for commands to process.
.Pp
Commands that operate on principals:
.Pp
.Bl -ohang -offset ind
.It Ar list Op Ar glob
will list the principals that match the
.Ar glob .
.It Ar query Ar princ
will display the principal
.Ar princ .
.It Ar mquery Ar glob Op Ar glob Ar ...
Outputs a list of principals.
.It Ar remove Ar princ
will remove the principal
.Ar princ .
.It Ar enable Ar princ
will enable the principal
.Ar princ
by removing the attribute
.Fl allow_tix .
.It Ar disable Ar princ
will disable the principal
.Ar princ
by adding the attribute
.Fl allow_tix .
.It Ar create_appid Ar princ Op Ar key=val ...
will create a principal for use by automated processes.
This principal will have no assigned passwd and will have a default
owner set to the calling user.
The key value pairs are the same as for
.Ar modify .
.It Ar create_user Ar princ
will create a principal with a random temporary password which is printed
to stdout. The password must be reset by the user via
.Xr kpasswd 1 .
.It Ar reset_password Ar princ
will reset the password of a principal to a random temporary password
which is printed to stdout. The password must be reset by the user via
.Xr kpasswd 1 .
.It Ar modify Ar princ Oo Ar key=val ... Oc
will modify a principal or its associated attributes.  The additional
arguments are a list of key value pairs indicating what is to be
set.
Set-based keys take a comma-separated list of values
.Pq interpreted as a set
and can also
take plus equals
.Pq +=
or minus equals
.Pq -=
to add or subtract elements from the set.
The following keys are defined for all principals: princ_expire_time,
pw_expiration, max_life, max_renewable_life, and attributes.
The following keys are defined for appids:
owner
.Pq set-based ,
desc,
cstraint
.Pq set-based .
.El
.Pp
Commands that operate on policies:
.Bl -ohang -offset ind
.It Ar listpols Op Ar glob
will list the policies that match
.Ar glob .
.El
.Pp
Commands that operate on ``features'':
.Bl -ohang -offset ind
.It add_feature Ar feature
Adds a ``feature'' flag.
.It has_feature Ar feature
Check to see if ``feature'' is present, i.e. has been added.
.El
.Pp
Commands that operate on hosts:
.Pp
.Bl -ohang -offset ind
.It create_host Ar name No realm Ar REALM Op No bootbinding Ar principal
Create a host in the krb5_admin database with the given realm name and
bootbinding. The realm is used for prestashed ticket access control and the
optional bootbinding principal is used to bind an ephemeral principal to a
host principal in the same realm.
.It bind_host Ar name Ar principal
Bind an existing host to the given ephemeral principal, this
entitles the host to negotiate its initial keys.
.El
.Sh EXAMPLES
To add
.Ar elric@IMRRYR.ORG
to the list of owners of the appid
.Ar webserver :
.Bd -literal
	$ krb5_admin modify webserver owner+=elric@IMRRYR.ORG
.Ed
.Sh SEE ALSO
.Xr knc 1 ,
.Xr krb5_admind 8 ,
.Xr krb5_keytab 8 ,
.Xr krb5_prestash 1 .
