#!/usr/pkg/bin/perl

use Getopt::Std;
use Sys::Hostname;
use Sys::Syslog;

use Kharon::Engine::Server;
use Krb5Admin::Utils qw/load_krb5hostd_config/;
use Krb5Admin::Krb5Host::Daemon;

use strict;
use warnings;

our $KRB5_KEYTAB_CONFIG	= '/etc/krb5/krb5_hostd.conf';

#
# These variables are expected to be set in the configuration file:

sub HELP_MESSAGE {
	exec("man krb5_hostd");
	exit(1);
}

sub usage {

	print STDERR "Usage: krb5_hostd [-c conf_file]\n";
	exit(1);
}

openlog('krb5_hostd', 'pid', 'auth');

my %opts;
getopts('c:v', \%opts) or usage();

my %config;
$config{config}			= $KRB5_KEYTAB_CONFIG;
$config{config}			= $opts{c}		if  defined($opts{c});
$config{config_provided}	= defined($opts{c});
$config{verbose}		= 1			if exists($opts{'v'});

load_krb5hostd_config(\%config);

Krb5Admin::Krb5Host::Daemon::run(\%config);
