#!/usr/pkg/bin/perl

use Getopt::Std;
use Sys::Hostname;
use Sys::Syslog;

use Kharon::Engine::Server;
use Krb5Admin::Krb5Host::Daemon;

use strict;
use warnings;

use constant {
	KRB5_KEYTAB_CONFIG	=> '/etc/krb5/krb5_hostd.conf',
	ACL_FILE                => '/etc/krb5/krb5_host.acl', # XXX TODO
};

#
# These variables are expected to be set in the configuration file:

our $verbose = 0;
our %user2service = ();
our @allowed_enctypes = ();
our @admin_users = ();
our %krb5_libs = ();
our %krb5_lib_quirks = ();
our $default_krb5_lib = ();
our %user_libs = ();
our $use_fetch = 0;
our $ktdir;
our $lockdir;

sub HELP_MESSAGE {
	exec("man krb5_hostd");
	exit(1);
}

sub usage {

	print STDERR "Usage: krb5_hostd\n";
	exit(1);
}

openlog('krb5_hostd', 'pid', 'auth');

do KRB5_KEYTAB_CONFIG if -f KRB5_KEYTAB_CONFIG;
# XXXrcd: fail if we can't read the configuration, I think.

my %config;
$config{verbose}		=  $verbose;
$config{user2service}		= \%user2service;
$config{allowed_enctypes}	= \@allowed_enctypes;
$config{admin_users}		= \@admin_users;
$config{krb5_libs}		= \%krb5_libs;
$config{krb5_lib_quirks}	= \%krb5_lib_quirks;
$config{default_krb5_lib}	=  $default_krb5_lib;
$config{user_libs}		= \%user_libs;
$config{use_fetch}		=  $use_fetch;
$config{ktdir}			=  $ktdir;
$config{lockdir}		=  $lockdir;

my %opts;
getopts('', \%opts) or usage();

Krb5Admin::Krb5Host::Daemon::run(\%config);
