#!/usr/bin/perl

use Krb5Admin::Krb5Host::Client;

use strict;
use warnings;
use Env;
use Sys::Hostname;
use Data::Dumper;

my $uname = getpwuid($<);
my $fqdn = hostname();

my $KINIT="/opt/heimdal/bin/kinit";
my $KTAB ="/var/spool/keytabs/$uname";
my $PRINC="$uname/$fqdn";

if (!defined($ENV{'KRB5CCNAME'})) {
	print "Execing\n";
	exec($KINIT, "-kt", $KTAB, $PRINC, $0, @ARGV);
	exit(1);
}

if (@ARGV != 1) {
	print "Missing hostname\n";
	print "usage: " . $0 . " <hostname>\n";
	exit(1);
}

eval {
	my $clnt = Krb5Admin::Krb5Host::Client->new($ARGV[0]);
	my $resp = $clnt->do_update();
};

# Maybe handle this a little better
# right now we just assume that all errors are recoverable
# and then we tell postfix to try again soon
# maybe not that great of an approach
if ($@) {
	print STDERR Dumper($@);
	exit(75);
}
